FROM openjdk:16-slim
MAINTAINER stupidzhang
ARG JAR_FILE=/target/*.jar
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
COPY ${JAR_FILE} /app.jar
EXPOSE 8896
HEALTHCHECK CMD curl -fs http://localhost:8888/health/check || exit 1
ENTRYPOINT ["sh","-c","java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8887 $JAVA_OPTS -jar /app.jar"]
